name: "test"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

permissions:
  contents: read
  issues: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore and cache Nix store
        uses: nix-community/cache-nix-action@v5
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-

      - name: Use nix
        uses: cachix/install-nix-action@v26

      - name: Azure login
        run: |
          nix develop --command az login --service-principal \
            -u ${{secrets.AZ_CLIENT_ID}} \
            -p ${{secrets.AZ_CLIENT_SECRET}}\
            -t ${{secrets.AZ_TENANT_ID}}

      - name: Run tests
        id: "test"
        continue-on-error: true
        env:
          TF_VAR_cloudflare_api_token: ${{ secrets.CF_API_TOKEN }}
          TF_VAR_cloudflare_zone_id: ${{ vars.CF_ZONE_ID }}
          TF_VAR_azure_location: ${{ vars.AZ_LOCATION }}
        run: |
          nix develop --command just test-ci 
          echo "failed=$(grep -c false results.json)" >> "$GITHUB_OUTPUT"
          echo "results=$(cat results.json)" >> "$GITHUB_OUTPUT"

      - uses: buildingcash/json-to-markdown-table-action@v1
        id: table
        with:
          json: ${{ steps.test.outputs.results }}

      - name: Open Issue
        uses: JasonEtco/create-an-issue@v2
        if: ${{ steps.test.outputs.failed != 0 }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SERVICE_TABLE: ${{ steps.table.outputs.table }}
        with:
          filename: .github/service-failure.md
          update_existing: true
          search_existing: open

